### ISSUE TITLE
[FEATURE]: Intégrer Stripe comme moyen de paiement

### ISSUE THREAD

**Issue by hkanoute** [NhiSty/challenge-stack-1#15]
### Is your feature request related to a problem? Please describe.

```markdown
No
```

### Describe the solution you'd like

Pouvoir effectuer des moyens de paiement via Stripe.

### Acceptance Criteria

- [x] I can make payment with stripe

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ChrisBradford2** [comment]
En attente des entités pour intégrer totalement le système de paiement.
