### ISSUE TITLE
[FEATURE]: Upload de document sur espace personnel

### ISSUE THREAD

**Issue by hkanoute** [NhiSty/challenge-stack-1#18]
### Describe the solution you'd like

Permettre au utilisateurs de pouvoir upload des documents sous format : pdf/png/jpeg sur son espace personelle

### Acceptance Criteria

- [ ] Je peux upload des documents depuis mon espace personelle

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ChrisBradford2** [comment]
Ticket traité dans le PR #58
