### ISSUE TITLE
[FEATURE]: Gestion des rôles

### ISSUE THREAD

**Issue by ThomasDev6** [NhiSty/challenge-stack-1#25]
### Is your feature request related to a problem? Please describe.

```markdown
Non
```

### Describe the solution you'd like

Séparer les différents rôle

### Acceptance Criteria

- [ ] Séparation des rôles 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ChrisBradford2** [comment]
La gestion des rôles se fait au cours du projet. Pas besoin d'un ticket. Je clôture.
